### ISSUE TITLE
Error when city not found

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/skill-weather#15]
**hey mycroft, when will it rain in waterbottle plastic**
An error occurred while processing a request in WeatherSkill

```
11:50:02.140 - mycroft.skills.core:wrapper:396 - ERROR - An error occurred while processing a request in WeatherSkill
Traceback (most recent call last):
File "/home/matthew/Documents/GitHub/mycroft-core/mycroft/skills/core.py", line 369, in wrapper
handler(self, message)
File "/opt/mycroft/skills/skill-weather/__init__.py", line 219, in handle_next_precipitation
report["full_location"]).get_forecast().get_weathers():
File "/opt/mycroft/skills/skill-weather/__init__.py", line 86, in daily_forecast
"query": query
File "/home/matthew/Documents/GitHub/mycroft-core/mycroft/api/__init__.py", line 48, in request
return self.send(params)
File "/home/matthew/Documents/GitHub/mycroft-core/mycroft/api/__init__.py", line 74, in send
return self.get_response(response)
File "/home/matthew/Documents/GitHub/mycroft-core/mycroft/api/__init__.py", line 84, in get_response
raise HTTPError(data, response=response)
HTTPError: {"cod":"404","message":"city not found"}
```

**Comment by MatthewScholefield** [comment]
I just verified, I can still reproduce the issue. But, it sometimes works if it cab derive a location from the string. Another that fails for me is `will it rain in somewhere`.

**Comment by ChristopherRogers1991** [comment]
I get this as well when I ask `what is the temperature in the living room?` (trying to get a thermostat reading):

```
14:00:22.742 - skill-weather:__handle_typed:690 - ERROR - Error: The location couldn't be found
Traceback (most recent call last):
  File "/opt/mycroft/skills/skill-weather/__init__.py", line 157, in weather_at_location
    "query": q
  File "/opt/mycroft/skills/skill-weather/__init__.py", line 138, in request
    resp = super().request(data)
  File "/home/chris/Code/mycroft-core/mycroft/api/__init__.py", line 65, in request
    return self.send(params)
  File "/home/chris/Code/mycroft-core/mycroft/api/__init__.py", line 147, in send 
    return self.get_response(response, no_refresh)
  File "/home/chris/Code/mycroft-core/mycroft/api/__init__.py", line 169, in get_response
    raise HTTPError(data, response=response)
requests.exceptions.HTTPError: {"cod":"404","message":"city not found"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft/skills/skill-weather/__init__.py", line 653, in __handle_typed
    report['lon']).get_weather()
  File "/opt/mycroft/skills/skill-weather/__init__.py", line 172, in weather_at_place
    response, trans_name = self.weather_at_location(name)
  File "/opt/mycroft/skills/skill-weather/__init__.py", line 163, in weather_at_location
    return self.weather_at_location(name)
  File "/opt/mycroft/skills/skill-weather/__init__.py", line 151, in weather_at_location
    raise ValueError('The location couldn\'t be found')
ValueError: The location couldn't be found
```

**Comment by chrisveilleux** [comment]
Weather skill uses a new API for geolocation now.  Closing
