### ISSUE TITLE
Location regex/adapt intent wont work

### ISSUE THREAD

**Issue by emphasize** [MycroftAI/skill-weather#168]
[UPDATE](https://github.com/MycroftAI/skill-weather/issues/168#issuecomment-890372481)

This is just a typo, 

instead of `self.location = message.data.get("location")` it has to be
`self.location = message.data.get("Location")` 
``` diff 
+ L 
- l
```

The optionally location lookup wont work with this call

**Comment by emphasize** [comment]
That said, this has revealed another problem
```
Traceback (most recent call last):
  File "/home/sweng/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-weather.emphasize/__init__.py", line 565, in handle_sunset
    dialog.build_sunset_dialog()
  File "/opt/mycroft/skills/skill-weather.emphasize/skill/dialog.py", line 170, in build_sunset_dialog
    now = now_local(tz=self.intent_data.geolocation["timezone"])
  File "/home/sweng/mycroft-core/mycroft/util/time.py", line 68, in now_local
    return datetime.now(tz)
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
```


=> now = now_local(tz=get_tz_info(self.intent_data.geolocation["timezone"]))

**Comment by emphasize** [comment]
This is indeed a Typo, but in `__init___.py`

Several intents (condition/storm/rain/...) have `.optionally("Location")` in their constructor while others go with `.optionally("location")`.

if you issue a condition request with a location information the location on the message object isn't processed correctly since
`self.location = message.data.get("location")`  [#](https://github.com/MycroftAI/skill-weather/blob/d4392e4243c289e527ea11315952f3b8552dcf29/skill/intent.py#L39)

**Comment by chrisveilleux** [comment]
I believe this issue to be resolved.  Can you confirm @emphasize?
