### ISSUE TITLE
Gui screens not staying up long enough to rea

### ISSUE THREAD

**Issue by builderjer** [MycroftAI/skill-weather#199]
When I ask for today's weather, the first screen should be the current temp.
The second screen should show today's forecast.

Instead, both screens show, but only for less than 1 second and then continues to the weekly forecast.

I think that when just asking for the weather "today", there should only be the two screens shown, and they need to stay up long enough to read.

This happens every time today's weather is asked, in any form that I have tried.

**Environment (please complete the following information):**
 - Device type: RPi4 
 - OS: KDE neon Unstable Edition (GNU/Linux 5.4.0-1050-raspi aarch64)
 - Mycroft-core version: 21.2.2

**Comment by builderjer** [comment]
I got this error also.

`15:23:39.350 | INFO     |  2188 | WeatherSkill | Speaking dialog: current-weather-local
 15:23:39.368 | INFO     |  2188 | Mark2 | Cancelling idle override
 15:23:39.781 | INFO     |  2188 | WeatherSkill | Speaking dialog: current-temperature-high-low
~~~~ | mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 | An error occurred while processing a request in Weather Skill
Traceback (most recent call last):
  File "/home/mycroft/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 122, in handle_current_weather
    self._report_current_weather(message)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 675, in _report_current_weather
    self._display_more_current_conditions(weather, weather_location)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 756, in _display_more_current_conditions
    self.gui.replace_page(page_name)
AttributeError: 'SkillGUI' object has no attribute 'replace_page'`
