### ISSUE TITLE
skill.error while asking for the weather

### ISSUE THREAD

**Issue by 0xsharkboy** [MycroftAI/skill-weather#202]
Hey, i'm on the picroft version and it returns a skill.error when i'm asking for the weather:

` 17:52:10.347 | INFO     |   784 | WeatherSkill | Speaking dialog: current-weather-local
 17:52:10.364 | ERROR    |   784 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 | skill.error
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 122, in handle_current_weather
    self._report_current_weather(message)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 667, in _report_current_weather
    self._speak_weather(dialog)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 1186, in _speak_weather
    self.speak_dialog(dialog.name, dialog.data, wait=True)
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1227, in speak_dialog
    self.dialog_renderer.render(key, data),
  File "/home/pi/mycroft-core/mycroft/dialog/dialog.py", line 110, in render
    line = line.format(**context)
KeyError: 'low_temperature'`

If someone can help me it would be very kind :D
I need to specify that I changed the laguage to French In the Mycroft's config file

**Comment by 0xsharkboy** [comment]
![image](https://user-images.githubusercontent.com/58356637/168870276-b5020044-691e-445f-8467-103dc36211fe.png)

**Comment by forslund** [comment]
I think this would be fixed by PR #118 or if the translate job is run by the mycroft team (translations seems to be updated on the translate server). @krisgesling might be able to say if it would be best to use the MR or if it's time to run the automated job.

**Comment by 0xsharkboy** [comment]
Okay thanks :D

**Comment by krisgesling** [comment]
Hey there, running the translation export now so this _should_ be fixed shortly.

**Comment by krisgesling** [comment]
I _think_ the translation scripts are having trouble with the new directory structure. 

So would accept a pull request in the meantime if you wanted to.

**Comment by 0xsharkboy** [comment]
Hey, I made my own traduction. Does it interest you ?

**Comment by krisgesling** [comment]
Yeah that would be great if you wanted to do a PR :)

**Comment by 0xsharkboy** [comment]
Okay, I juste don't know how to upload this

**Comment by krisgesling** [comment]
Hey if you're new to working with git there are some good [guides from Github](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) that will help you get started. 

If you've made the changes in the Skill (and this is the only change you've made), you can fork the repo at the top of this page, then you'd want to run something like:
```
cd /opt/mycroft/skills/mycroft-weather.mycroftai/
git remote add sharkboy https://github.com/SharkBoy69-CS/skill-weather/
git checkout -b bugfix/french-translations
git commit -am "Update French translations"
git push sharkboy bugfix/french-translations
```

**Comment by 0xsharkboy** [comment]
Hey, thanks ! Is it that ? https://github.com/SharkBoy69-CS/skill-weather

**Comment by valvin1** [comment]
hello, i did the same issue and discover that the fix provided the 2nd of june was not yet published on a french install. I had to:

```
cd /opt/mycroft/skills/mycroft-weather.mycroftai/
git pull
Mise à jour 481e6d4..9acb334
```
why the command which update skills didn't update automatically ?

**Comment by apennamen** [comment]
Hello,

Starting with a fresh install of picroft, and switching to french, I stumbled upon the same issue.
The weather skill was pointing to the 20.08 branch instead of the 21.02.

After checking out the last branch, the error vanished.

Regards,
AP
